import numpy as np

l0 = np.array(
    [
        "animal",
        "artifact",
        "entity",
        "fruit",
        "fungus",
        "geological formation",
        "person",
        "plant",
    ],
    dtype="<U71",
)
l1 = np.array(
    [
        "acorn",
        "cliff",
        "commodity",
        "covering",
        "creation",
        "decoration",
        "ear",
        "earthstar",
        "edible fruit",
        "explorer",
        "fabric",
        "gyromitra",
        "hen-of-the-woods",
        "hip",
        "instrumentality",
        "invertebrate",
        "natural depression",
        "natural elevation",
        "round shape",
        "seed",
        "sheet",
        "shore",
        "solid",
        "spring",
        "structure",
        "substance",
        "surface",
        "vascular plant",
        "vertebrate",
        "visual signal",
    ],
    dtype="<U71",
)

l2 = np.array(
    [
        "acorn",
        "adornment",
        "altar",
        "amphibian",
        "apple",
        "aquatic vertebrate",
        "arch",
        "area",
        "arthropod",
        "banana",
        "berry",
        "bird",
        "board",
        "bridge",
        "buckeye",
        "building",
        "building complex",
        "citrus",
        "cliff",
        "cloak",
        "cloth covering",
        "clothing",
        "coelenterate",
        "coil",
        "column",
        "connection",
        "consumer goods",
        "container",
        "conveyance",
        "custard apple",
        "defensive structure",
        "design",
        "device",
        "diver",
        "ear",
        "earthstar",
        "echinoderm",
        "equipment",
        "establishment",
        "floor cover",
        "food",
        "footwear",
        "fountain",
        "furnishing",
        "geyser",
        "grain",
        "gyromitra",
        "hen-of-the-woods",
        "hip",
        "horizontal surface",
        "housing",
        "implement",
        "jackfruit",
        "lakeside",
        "landing",
        "light",
        "mammal",
        "mask",
        "memorial",
        "mollusk",
        "mountain",
        "obstruction",
        "oilseed",
        "piece of cloth",
        "pineapple",
        "pomegranate",
        "product",
        "promontory",
        "protective covering",
        "reptile",
        "ridge",
        "screen",
        "seashore",
        "shelter",
        "spermatophyte",
        "sphere",
        "supporting structure",
        "system",
        "toiletry",
        "top",
        "tower",
        "valley",
        "velvet",
        "wool",
        "worm",
        "wrapping",
    ],
    dtype="<U71",
)

l3 = np.array(
    [
        "African chameleon",
        "African crocodile",
        "African elephant",
        "African grey",
        "African hunting dog",
        "American alligator",
        "American black bear",
        "American chameleon",
        "American coot",
        "American egret",
        "American lobster",
        "Arabian camel",
        "Arctic fox",
        "CD player",
        "Chihuahua",
        "Dungeness crab",
        "European fire salamander",
        "French loaf",
        "Gila monster",
        "Granny Smith",
        "Indian cobra",
        "Indian elephant",
        "Loafer",
        "Madagascar cat",
        "Mexican hairless",
        "Newfoundland",
        "Pomeranian",
        "Sealyham terrier",
        "Siberian husky",
        "abacus",
        "abaya",
        "academic gown",
        "accordion",
        "acorn",
        "admiral",
        "agama",
        "aircraft carrier",
        "albatross",
        "alligator lizard",
        "alp",
        "altar",
        "ambulance",
        "analog clock",
        "anemone fish",
        "artichoke",
        "ashcan",
        "baboon",
        "badger",
        "bagel",
        "bakery",
        "balance beam",
        "bald eagle",
        "balloon",
        "ballplayer",
        "banana",
        "banded gecko",
        "bannister",
        "barbell",
        "barber chair",
        "barn",
        "barometer",
        "barracouta",
        "barrel",
        "barrow",
        "basketball",
        "basset",
        "bath towel",
        "bathing cap",
        "bathtub",
        "beacon",
        "bearskin",
        "bell cote",
        "bell pepper",
        "bicycle-built-for-two",
        "bighorn",
        "binoculars",
        "birdhouse",
        "bison",
        "black grouse",
        "black stork",
        "black swan",
        "boathouse",
        "bonnet",
        "book jacket",
        "bookcase",
        "bow",
        "box turtle",
        "brass",
        "brassiere",
        "breakwater",
        "breastplate",
        "broccoli",
        "broom",
        "brown bear",
        "bubble",
        "bucket",
        "buckeye",
        "bulbul",
        "bulletproof vest",
        "bullfrog",
        "butcher shop",
        "butternut squash",
        "cab",
        "caldron",
        "cannon",
        "canoe",
        "capuchin",
        "cardigan",
        "cardoon",
        "carousel",
        "castle",
        "cauliflower",
        "chain",
        "chain mail",
        "chain saw",
        "chainlink fence",
        "cheetah",
        "chest",
        "chimpanzee",
        "china cabinet",
        "chocolate sauce",
        "church",
        "cicada",
        "cinema",
        "cliff",
        "cliff dwelling",
        "cloak",
        "cock",
        "cockroach",
        "coho",
        "coil",
        "collie",
        "colobus",
        "comic book",
        "common iguana",
        "common newt",
        "conch",
        "confectionery",
        "coral reef",
        "corn",
        "cougar",
        "cowboy hat",
        "coyote",
        "crane",
        "crash helmet",
        "croquet ball",
        "crossword puzzle",
        "crutch",
        "cucumber",
        "cup",
        "custard apple",
        "daisy",
        "dam",
        "desk",
        "dhole",
        "diamondback",
        "diaper",
        "dining table",
        "dishrag",
        "dock",
        "dogsled",
        "dome",
        "doormat",
        "dough",
        "drum",
        "drumstick",
        "dumbbell",
        "ear",
        "earthstar",
        "echidna",
        "eel",
        "electric ray",
        "entertainment center",
        "espresso",
        "fire engine",
        "fire screen",
        "fireboat",
        "flagpole",
        "flatworm",
        "football helmet",
        "fountain",
        "four-poster",
        "fox squirrel",
        "frilled lizard",
        "frying pan",
        "fur coat",
        "gar",
        "garter snake",
        "gazelle",
        "geyser",
        "giant panda",
        "gibbon",
        "goblet",
        "golden retriever",
        "goldfinch",
        "goldfish",
        "golf ball",
        "gondola",
        "gong",
        "goose",
        "gorilla",
        "gown",
        "grand piano",
        "grasshopper",
        "great grey owl",
        "great white shark",
        "green lizard",
        "green snake",
        "greenhouse",
        "grey fox",
        "grey whale",
        "grocery store",
        "guacamole",
        "guenon",
        "guillotine",
        "gyromitra",
        "hair slide",
        "hammer",
        "hammerhead",
        "harmonica",
        "hartebeest",
        "harvester",
        "harvestman",
        "hatchet",
        "hay",
        "head cabbage",
        "hen-of-the-woods",
        "hip",
        "hippopotamus",
        "hog",
        "home theater",
        "honeycomb",
        "hoopskirt",
        "hornbill",
        "horned viper",
        "horse cart",
        "hot pot",
        "hotdog",
        "howler monkey",
        "hummingbird",
        "ibex",
        "ice bear",
        "ice lolly",
        "impala",
        "indigo bunting",
        "indri",
        "iron",
        "jack-o'-lantern",
        "jackfruit",
        "jaguar",
        "jay",
        "jellyfish",
        "jersey",
        "jigsaw puzzle",
        "jinrikisha",
        "killer whale",
        "kimono",
        "king crab",
        "king penguin",
        "king snake",
        "kit fox",
        "knee pad",
        "knot",
        "koala",
        "komondor",
        "lab coat",
        "lacewing",
        "ladybug",
        "lakeside",
        "langur",
        "laptop",
        "leafhopper",
        "leatherback turtle",
        "lemon",
        "leopard",
        "library",
        "lifeboat",
        "limpkin",
        "lion",
        "lionfish",
        "llama",
        "loggerhead",
        "lorikeet",
        "lumbermill",
        "lynx",
        "macaque",
        "macaw",
        "magpie",
        "maillot",
        "malinois",
        "manhole cover",
        "maraca",
        "marmoset",
        "marmot",
        "mashed potato",
        "mask",
        "maypole",
        "maze",
        "medicine chest",
        "meerkat",
        "megalith",
        "menu",
        "microwave",
        "military uniform",
        "minibus",
        "miniskirt",
        "minivan",
        "mitten",
        "mixing bowl",
        "mobile home",
        "monarch",
        "monastery",
        "mongoose",
        "mortarboard",
        "mosque",
        "mountain bike",
        "mountain tent",
        "moving van",
        "mud turtle",
        "mushroom",
        "nail",
        "necklace",
        "night snake",
        "obelisk",
        "oboe",
        "orange",
        "orangutan",
        "ostrich",
        "otter",
        "ox",
        "oxcart",
        "oystercatcher",
        "paddle",
        "paddlewheel",
        "padlock",
        "pajama",
        "palace",
        "panpipe",
        "parachute",
        "park bench",
        "parking meter",
        "passenger car",
        "patas",
        "patio",
        "pedestal",
        "pelican",
        "pencil box",
        "perfume",
        "photocopier",
        "pier",
        "pill bottle",
        "pineapple",
        "ping-pong ball",
        "plastic bag",
        "plate",
        "platypus",
        "pole",
        "police van",
        "pomegranate",
        "pool table",
        "porcupine",
        "pot",
        "potpie",
        "power drill",
        "prayer rug",
        "pretzel",
        "prison",
        "promontory",
        "ptarmigan",
        "quail",
        "quill",
        "quilt",
        "racer",
        "ram",
        "rapeseed",
        "red fox",
        "red wine",
        "red wolf",
        "red-breasted merganser",
        "reel",
        "restaurant",
        "ringneck snake",
        "robin",
        "rock beauty",
        "rock crab",
        "rocking chair",
        "rubber eraser",
        "ruddy turnstone",
        "ruffed grouse",
        "rugby ball",
        "sandbar",
        "sarong",
        "scabbard",
        "schipperke",
        "schooner",
        "scoreboard",
        "screw",
        "scuba diver",
        "sea anemone",
        "sea lion",
        "sea urchin",
        "seashore",
        "seat belt",
        "shoe shop",
        "shoji",
        "shopping basket",
        "shopping cart",
        "shovel",
        "shower curtain",
        "siamang",
        "sidewinder",
        "ski",
        "skunk",
        "sleeping bag",
        "sliding door",
        "slot",
        "slug",
        "snorkel",
        "snow leopard",
        "snowmobile",
        "soccer ball",
        "solar dish",
        "sombrero",
        "sorrel",
        "space shuttle",
        "spaghetti squash",
        "spatula",
        "speedboat",
        "spider monkey",
        "spider web",
        "sports car",
        "spotlight",
        "spotted salamander",
        "stage",
        "starfish",
        "steam locomotive",
        "steel arch bridge",
        "stingray",
        "stole",
        "stone wall",
        "stove",
        "strainer",
        "strawberry",
        "streetcar",
        "stretcher",
        "studio couch",
        "stupa",
        "sturgeon",
        "submarine",
        "suit",
        "sundial",
        "sunglass",
        "suspension bridge",
        "swab",
        "swimming trunks",
        "swing",
        "table lamp",
        "tailed frog",
        "tank",
        "tarantula",
        "television",
        "tench",
        "tennis ball",
        "terrapin",
        "thatch",
        "theater curtain",
        "thresher",
        "throne",
        "thunder snake",
        "tiger",
        "tile roof",
        "timber wolf",
        "titi",
        "tobacco shop",
        "torch",
        "totem pole",
        "toucan",
        "tractor",
        "traffic light",
        "trailer truck",
        "tray",
        "tree frog",
        "triceratops",
        "tricycle",
        "trifle",
        "tripod",
        "triumphal arch",
        "tub",
        "turnstile",
        "tusker",
        "umbrella",
        "vacuum",
        "valley",
        "vase",
        "vault",
        "velvet",
        "vestment",
        "viaduct",
        "volcano",
        "volleyball",
        "vulture",
        "walking stick",
        "wallaby",
        "wardrobe",
        "warplane",
        "warthog",
        "water buffalo",
        "water jug",
        "water ouzel",
        "water snake",
        "water tower",
        "weasel",
        "whiptail",
        "whistle",
        "white wolf",
        "wig",
        "window screen",
        "window shade",
        "wine bottle",
        "wing",
        "wood rabbit",
        "wooden spoon",
        "wool",
        "worm fence",
        "wreck",
        "yawl",
        "yurt",
        "zebra",
        "zucchini",
    ],
    dtype="<U71",
)


dummy_data = {
    "stimuli": np.random.uniform(low=0, high=1, size=(1750, 128, 128)),
    "stimuli_test": np.random.uniform(low=0, high=1, size=(120, 128, 128)),
    "responses": np.random.uniform(low=0, high=1, size=(1750, 8428)),
    "responses_test": np.random.uniform(low=0, high=1, size=(120, 8428)),
    "roi": (np.random.randint(low=1, high=7, size=(8428,))),
    "roi_names": np.array(
        ["Other", "V1", "V2", "V3", "V3A", "V3B", "V4", "LatOcc"], dtype="<U6"
    ),
    "train_labels": np.stack(
        [
            np.random.choice(l0, 1750),
            np.random.choice(l1, 1750),
            np.random.choice(l2, 1750),
            np.random.choice(l3, 1750),
        ],
        axis=1,
    ),
    "test_labels": np.stack(
        [
            np.random.choice(l0, 120),
            np.random.choice(l1, 120),
            np.random.choice(l2, 120),
            np.random.choice(l3, 120),
        ],
        axis=1,
    ),
}
