wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1629208266
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.11
      5: 0.12.0
      8:
      - 1
      - 5
